spring.config.import=optional:file:.env[.properties]
spring.application.name=cinema
server.port=9090
api.version=1.43

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cinema}
spring.datasource.username=${DB_USERNAME:cinema_manager}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

aws.s3.bucket=${AWS_S3_BUCKET:cinema-storage-bucket}
aws.eventBridge.bus=${AWS_EVENTBRIDGE_BUS:default}

app.jwt.secret=${JWT_SECRET:U3VwZXJM b25nRW5jb2RlZEJhc2U2NFNlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9uTjY=}
app.jwt.expiration-ms=${JWT_EXPIRATION:86400000}
